version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: solana_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exchange_db
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7
    container_name: solana_queue
    ports:
      - "6379:6379"

